/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.ConsultaDAO;
import Model.Consulta;
import Model.Funcionario;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nicolas
 */
public class ViewPrincipal extends javax.swing.JFrame {

    private Funcionario funcionarioLogado;
    

    /**
     * Creates new form ViewPrincipal
     */
    public ViewPrincipal(Funcionario funcionario){
        this.funcionarioLogado = funcionario;
        initComponents();
        this.preencherTabela();
        setLocationRelativeTo(null);
    }

    public Funcionario getFuncionarioLogado() {
        return funcionarioLogado;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableConsultas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnCadMed = new javax.swing.JButton();
        btnCadFuncionario = new javax.swing.JButton();
        btnConsultas = new javax.swing.JButton();
        btnCadPaciete = new javax.swing.JButton();
        btnEditarConsulta = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(85, 186, 126));

        jScrollPane1.setBackground(new java.awt.Color(46, 104, 69));

        jTableConsultas.setBackground(new java.awt.Color(46, 104, 69));
        jTableConsultas.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTableConsultas.setForeground(new java.awt.Color(255, 255, 255));
        jTableConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Paciente", "Medico", "Atedente", "Data e Hora", "Observaçao"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableConsultas);

        jLabel1.setFont(new java.awt.Font("Lucida Handwriting", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Belle Curls - Consultas");

        btnCadMed.setBackground(new java.awt.Color(255, 255, 255));
        btnCadMed.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnCadMed.setForeground(new java.awt.Color(0, 0, 0));
        btnCadMed.setText("Cad. Medico");
        btnCadMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadMedActionPerformed(evt);
            }
        });

        btnCadFuncionario.setBackground(new java.awt.Color(255, 255, 255));
        btnCadFuncionario.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnCadFuncionario.setForeground(new java.awt.Color(0, 0, 0));
        btnCadFuncionario.setText("Cad. Funcionario");
        btnCadFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadFuncionarioActionPerformed(evt);
            }
        });

        btnConsultas.setBackground(new java.awt.Color(255, 255, 255));
        btnConsultas.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnConsultas.setForeground(new java.awt.Color(0, 0, 0));
        btnConsultas.setText("+ Consultas");
        btnConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultasActionPerformed(evt);
            }
        });

        btnCadPaciete.setBackground(new java.awt.Color(255, 255, 255));
        btnCadPaciete.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnCadPaciete.setForeground(new java.awt.Color(0, 0, 0));
        btnCadPaciete.setText("Cad. Paciente");
        btnCadPaciete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadPacieteActionPerformed(evt);
            }
        });

        btnEditarConsulta.setBackground(new java.awt.Color(255, 255, 255));
        btnEditarConsulta.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnEditarConsulta.setForeground(new java.awt.Color(0, 0, 0));
        btnEditarConsulta.setText("Editar");

        btnDeletar.setBackground(new java.awt.Color(255, 255, 255));
        btnDeletar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnDeletar.setForeground(new java.awt.Color(0, 0, 0));
        btnDeletar.setText(" Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(btnEditarConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(297, 297, 297))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCadFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCadMed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCadPaciete, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                        .addGap(179, 179, 179)))
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(383, 383, 383))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCadPaciete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCadMed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCadFuncionario)
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditarConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultasActionPerformed
        // TODO add your handling code here:
        Funcionario funcionarioLogado = getFuncionarioLogado();

    // Cria a ViewConsulta passando o funcionário logado como parâmetro
        new ViewCadastrarConsulta(funcionarioLogado).setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btnConsultasActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        // TODO add your handling code here:
        this.deletarConsulta();
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnCadPacieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadPacieteActionPerformed
        // TODO add your handling code here:
        new ViewCadastrarPaciente().setVisible(true);
    }//GEN-LAST:event_btnCadPacieteActionPerformed

    private void btnCadMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadMedActionPerformed
        // TODO add your handling code here:
        new ViewCadastrarMedico().setVisible(true);
    }//GEN-LAST:event_btnCadMedActionPerformed

    private void btnCadFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadFuncionarioActionPerformed
        // TODO add your handling code here:
        new ViewCadastrarFuncionario().setVisible(true);
    }//GEN-LAST:event_btnCadFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPrincipal(null).setVisible(true);
            }
        });
    }
    
    
    
    public void preencherTabela() {
    DefaultTableModel modelo = new DefaultTableModel();
    modelo.addColumn("ID");
    modelo.addColumn("Paciente");
    modelo.addColumn("Médico");
    modelo.addColumn("Atendente");
    modelo.addColumn("Data da Consulta");
    modelo.addColumn("Observações");
        try {
            ConsultaDAO dao = new ConsultaDAO();
            List<Consulta> consultas = dao.listarConsultas();

            for (Consulta consulta : consultas) {
                Object[] dados = new Object[6];
                dados[0] = consulta.getId();
                dados[1] = consulta.getPaciente();
                dados[2] = consulta.getMedico();
                dados[3] = consulta.getAtendente();
                dados[4] = consulta.getDataConsulta();
                dados[5] = consulta.getObservacoes();
                modelo.addRow(dados);
            }

            jTableConsultas.setModel(modelo);
            
        } catch (Exception e) {
        }
}

    public void deletarConsulta() {
    int linhaSelecionada = jTableConsultas.getSelectedRow();
    if (linhaSelecionada != -1) {
        int idConsulta = (int) jTableConsultas.getValueAt(linhaSelecionada, 0);
        ConsultaDAO daoConsulta = new ConsultaDAO();
        daoConsulta.excluirConsulta(idConsulta);
        DefaultTableModel modelo = (DefaultTableModel) jTableConsultas.getModel();
        modelo.removeRow(linhaSelecionada);
    } else {
        JOptionPane.showMessageDialog(null, "Selecione uma consulta para excluir.");
    }
}


    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadFuncionario;
    private javax.swing.JButton btnCadMed;
    private javax.swing.JButton btnCadPaciete;
    private javax.swing.JButton btnConsultas;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnEditarConsulta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableConsultas;
    // End of variables declaration//GEN-END:variables
}
